symbol = input('\nSymbol:  ');
from_d = input('\nFrom Date: ', 's');
to_d = input('\nUntil Date: ', 's');
query = sprintf([ 'SELECT broker_id, name, tbuy, tsell, net ' ...
          'FROM (SELECT broker_id , SUM( buy)  AS tbuy, SUM( sell ) AS tsell , SUM( buy ) - SUM(sell ) AS net ' ...
                'FROM  bsreport ' ...
                'WHERE  company_id = %d AND date >= "%s" AND date <= "%s" ' ...
                'GROUP BY  broker_id ' ...
                'ORDER BY net ASC ' ...
                'LIMIT 20) AS a '  ...
            'JOIN brokers ON a.broker_id = brokers.id' ], symbol, from_d, to_d);

result = sql_query(query);
bsr_bybroker_chart([cell2mat(result(:,3)), cell2mat(result(:,4))*-1, cell2mat(result(:,5))], result(:,2));