symbol = input('\nSymbol:  ');
N = input('N: ');
%from_d = input('\nFrom Date: ', 's');
%to_d = input('\nUntil Date: ', 's');
query_template = [ 'SELECT date, SUM( tnet ) ' ...
                   'FROM (SELECT * ' ...
                          'FROM ( ' ...
                            'SELECT date, broker_id, SUM( buy ) - SUM( sell ) AS tnet ' ...
                            'FROM bsreport ' ...
                            'WHERE company_id = %d ' ...
                            'GROUP BY broker_id, date ' ...
                            ') AS b ' ...
                   'JOIN ( ' ...
                        'SELECT broker_id AS id ' ...
                        'FROM bsreport ' ...
                        'WHERE company_id = %d ' ...
                        'GROUP BY broker_id ' ...
                        'ORDER BY SUM( buy ) - SUM( sell ) %s ' ...
                        'LIMIT %d ' ...
                   ') AS a ' ...
                   'ON a.id = b.broker_id ' ...
                ') AS c ' ...
                'GROUP BY date' ];
 
scrsz = get(0, 'ScreenSize');
figure('Position', [50 100 scrsz(3)*0.5 scrsz(4)*0.5]);        

hold on

query = sprintf(query_template, symbol, symbol, 'DESC', N);
tbuy = sql_query(query);

query = sprintf(query_template, symbol, symbol, 'ASC', N);
tsell = sql_query(query);
title_s = sprintf('Top %d ¥D¤O for %d', N, symbol);
bsr_sum_chart(cell2mat(tbuy(:,2)), cell2mat(tsell(:,2)), tsell(:,1), title_s)

hold off